name: CheckLinks
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checklinks:
    name: Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Setup Rubygems, Bundler, jekyll
        run: | 
          gem update --system --no-document
          gem update bundler --no-document
          gem install jekyll bundler
          bundle install
      - name: Build jekyll website with drafts
        run: bundle exec jekyll build --drafts
      - name: Check for broken links
        run: |
          bundle exec htmlproofer --log-level :debug ./_site
        continue-on-error: true